### ISSUE TITLE
Dynamically generates pages cause git errors

### ISSUE THREAD

**Issue by jclusso** [ayushn21/bridgetown-sitemap#5] opened 2023-09-18 21:21 UTC
https://github.com/ayushn21/bridgetown-sitemap/blob/1d4c1d675efa507d90252acd54c03819ef3191da/lib/bridgetown/resource/base.rb#L12-L20

Dynamically generated pages cause this to fail I think because there is no actual page.

**Comment by ayushn21** [comment] 2023-09-19 10:07
Hey @jclusso, could you please share some more details about the error you're seeing? Ideally if you could share a repo in which I can reproduce the error that would be best.

I'm using this gem in one of my sites which is almost entirely dynamically generated pages so I reckon the problem is something else.

**Comment by jclusso** [comment] 2023-09-19 12:16
@ayushn21 here is the exact error that we get

```
Use '--' to separate paths from revisions, like this:                                             'git <command> [<revision>...] -- [<file>...]'                                                    
fatal: ambiguous argument 'autopilot.html': unknown revision or path not in the working tree.
```

and here is a snippet of the code we use to generate the pages.

```ruby
blog_posts.each do |blog_post|
  add_resource :blog_posts, "#{blog_post.dig('slug', 'current')}.html" do
    layout :post
    title "#{blog_post['title']}"
    locale blog_post['language']
    body blog_post['body']
  end
end
```

**Comment by ayushn21** [comment] 2023-09-19 12:56
Any chance you could share a repository with this error please? It'd really help me out, I'm flying blind here otherwise ... never seen this issue before.

**Comment by jclusso** [comment] 2023-09-19 13:36
@ayushn21 sure, let me see if I can replicate in an example repo for you.

**Comment by jclusso** [comment] 2023-09-19 13:56
@ayushn21 here you go. https://github.com/jclusso/bt_sitemap_issue

**Comment by ayushn21** [comment] 2023-09-19 15:14
That @jclusso that was super helpful. I haven't encountered this issue in the past because in my sites I've been generating page objects that I add to the `site.pages` collection in a builder.

In your site you're dynamically adding `resource`s which wasn't a case I'd considered.

I've pushed a fix to `main` now so if you point your Gemfile to the `main` branch it should fix your issue. I haven't written a test for it yet so I don't want to cut a release until I've done that.

I'll leave this issue open so I don't forget. Hope this unblocks you for now though!

Let me know if you run into any more issues.

**Comment by jclusso** [comment] 2023-09-19 15:22
Yep, seems to have fixed it! Thanks a ton

**Closed as completed** 2024-03-23 03:37 UTC
